[package]
name = "gumby-rs"
version = "0.1.0"
authors = ["justincremer <jacremer@live.com>"]
edition = "2018"

[dependencies]
hyper = "0.10.1"
html5ever = "0.21.0"
url = "0.2.37"

[[bin]]
name = "gumby"
path = "bin/main.rs"